# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'http-lzakharov-github-io'

menu:
- {name: 'Posts', path: 'menu', url: 'posts.html'}
- {name: 'Resume', path: 'menu', url: 'resume.html'}
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/lzakharov'}
# - {icon: 'twitter', link: 'https://twitter.com/'}
# - {icon: 'linkedin', link: 'http://www.linkedin.com/in/'}
- {icon: 'envelope', link: 'mailto:l.j.zakharov@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
